name: DeathRevenge
version: '1.0'
main: com.deathrevenge.DeathRevenge
api-version: '1.21'
description: A plugin that gives players a chance for revenge after death
commands:
  deathrevenge:
    description: Shows information about the DeathRevenge plugin
    aliases: [dr]
    usage: /<command> 